spring.application.name=app

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/wellnest_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:root}

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.sql.init.mode=always
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Allow large POSTs for Base64 images
server.tomcat.max-http-post-size=10MB
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# ===== EMAIL CONFIG (Gmail example) =====
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${SPRING_MAIL_USERNAME:your-email@gmail.com}
spring.mail.password=${SPRING_MAIL_PASSWORD:your-app-password}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000

# Resend API Config (HTTP-based fallback)
resend.api.key=${RESEND_API_KEY:}
resend.from.email=${RESEND_FROM_EMAIL:Wellnest <onboarding@resend.dev>}

# Frontend base URL for building reset link
app.frontend.base-url=${FRONTEND_URL:http://localhost:3000}

# ===== AI CONFIG (Groq - Llama 3) =====
# Uses Environment Variable GROQ_API_KEY if exists, otherwise uses local key
groq.api.key=${GROQ_API_KEY:your-groq-api-key}
openrouter.api.key=${OPENROUTER_API_KEY:your-openrouter-api-key}
huggingface.api.key=${HUGGINGFACE_API_KEY:your-huggingface-api-key}


# ===== ADMIN CREDENTIALS =====
admin.username=${ADMIN_EMAIL:admin123@gmail.com}
admin.password=${ADMIN_PASSWORD:admin123}

# ===== JWT SECURITY =====
app.jwt.secret=${JWT_SECRET:this_is_a_very_long_secret_key_change_it_to_secure_one_123456}

# ===== GOOGLE OAUTH CONFIG =====
google.client.id=${GOOGLE_CLIENT_ID:824393698796-2a2k17e527hbnd9irvhjv72pnngc5jc7.apps.googleusercontent.com}

# ===== RATE LIMIT CONFIG =====
rate-limit.auth.capacity=${RATE_LIMIT_AUTH_CAPACITY:2000}
rate-limit.anon.capacity=${RATE_LIMIT_ANON_CAPACITY:300}

